---
- name: squid をインストールする
  ansible.builtin.apt:
    name: squid
    state: present
    update_cache: true

- name: squid.conf を配置する
  ansible.builtin.template:
    src: squid.conf.j2
    dest: /etc/squid/squid.conf
    owner: root
    group: root
    mode: "0644"
    backup: true
  notify: restart squid

- name: squid を有効化して起動する
  ansible.builtin.service:
    name: squid
    state: started
    enabled: true
